<?php

namespace QLIO\GestionBundle\Repository;

/**
 * air_pickingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class air_pickingRepository extends \Doctrine\ORM\EntityRepository
{
}
