<?php

namespace QLIO\GestionBundle\Repository;

/**
 * contenir_visserieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contenir_visserieRepository extends \Doctrine\ORM\EntityRepository
{
}
