<?php

namespace QLIO\GestionBundle\Repository;

/**
 * sachetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sachetRepository extends \Doctrine\ORM\EntityRepository
{
}
