<?php

namespace QLIO\GestionBundle\Repository;

/**
 * typevisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typevisRepository extends \Doctrine\ORM\EntityRepository
{
}
